# Generated by Django 5.1.4 on 2025-03-06 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='cloth',
        ),
        migrations.AddField(
            model_name='size',
            name='color',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='size',
            name='customer',
            field=models.ForeignKey(default='harry', on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='tailorapp.customer'),
        ),
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.CharField(default='washinwear', max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='chest',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='size',
            name='neck',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='size',
            name='shalwar_length',
            field=models.IntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='size',
            name='shoulder_length',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='size',
            name='sleeve_length',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='size',
            name='sleeve_width',
            field=models.IntegerField(default=34),
        ),
        migrations.AlterField(
            model_name='size',
            name='suit_length',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='size',
            name='waist',
            field=models.IntegerField(default=23),
        ),
        migrations.DeleteModel(
            name='Cloth',
        ),
    ]
