# Generated by Django 5.1.4 on 2025-03-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailorapp', '0002_remove_size_cloth_size_color_size_customer_size_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='tailorapp.customer'),
        ),
    ]
